### ISSUE TITLE
VSCode linting configuration needs to be udpated

### ISSUE THREAD

**Issue by ehsteve** [HERMES-SOC/hermes_core#109]
All uses of the `python.linting` configuration namespace is now deprecated by Visual Studio code. See this [article](https://github.com/microsoft/vscode-python/wiki/Migration-to-Python-Tools-Extensions). Python linting tools have been moved to extensions.

**Comment by Alrobbertz** [comment]
@dbarrous, sorry I just saw you assigned this to yourself. I started a PR #110 but feel free to commandeer the PR or suggest edits. I did my best, but you're probably more familiar with the extensions handling than I am.

**Comment by dbarrous** [comment]
Sounds good, the PR looks good needs a few tweaks. Added my review to the PR with suggestions.
