### ISSUE TITLE
The timedata class function save() should return a path object and not a string

### ISSUE THREAD

**Issue by ehsteve** [HERMES-SOC/hermes_core#116]
Our standard is to use paths everywhere instead of strings to have more portable code.

The title is self explanatory. This would make it easier to test whether a file was created by using the function `is_file` for example.

**Comment by Alrobbertz** [comment]
I have completed and merged the required changes in Core through #117 . 

I have shown that the changes work for the instrument repositories though EEA https://github.com/HERMES-SOC/hermes_eea/pull/41. I will replicate these changes for the other instrument repos and merge them all at the same time.

**Comment by Alrobbertz** [comment]
Closed with 

◦ #117 
◦ https://github.com/HERMES-SOC/hermes_eea/pull/41
◦ https://github.com/HERMES-SOC/hermes_merit/pull/22
◦ https://github.com/HERMES-SOC/hermes_spani/pull/27
◦ https://github.com/HERMES-SOC/hermes_nemisis/pull/25
