### ISSUE TITLE
parse_science_filename does not recognize NEM or nem

### ISSUE THREAD

**Issue by kbromund** [HERMES-SOC/hermes_core#120]
parse_science_filename needs to recognize instrument=="NEM" in L0 files, and store "nem" in the "instrument" element of the returned dictionary.

**Comment by kbromund** [comment]
OK, I'll try that.  After posting the issue, I tried making this change to __init__.py in hermes_nemisis:
-INST_SHORTNAME = "nms"
-INST_TARGETNAME = "MAG"
+INST_SHORTNAME = "nem"
+INST_TARGETNAME = "NEM"
but it didn't work.  IMHO, it should have worked, rather than having these hardcoded in hermes_core.

**Comment by dbarrous** [comment]
It's hardcoded into the `hermes_core` because core should have what instruments since it's used to figure out which instrument package to use within the differents lambda function. The shortnames on the instrument package are used for your reference within that package.

**Comment by kbromund** [comment]
HMM.. OK... I tried installing Damian's PR:
pip install hermes_core@git+https://github.com/dbarrous/hermes_core.git@24-chage-shortname-nemisis
but that doesn't have your fix for allowing two TimeSeries:  I get the message:
TypeError: timeseries must be a `astropy.timeseries.TimeSeries` object.
Are the two merged together someplace??

**Comment by Alrobbertz** [comment]
Hi Ken, I just merged Damian's changes into my branch for #114. So that branch should now have both the naming changes as well as the TimeSeries changes.

**Comment by kbromund** [comment]
Thanks, that works.  dumb question.  If it's issue #114, why is the branch name 113-multiple-timeseries?

**Comment by Alrobbertz** [comment]
The issue was #113, the PR is #114. So the branch name matches the Issue number, but not the PR number. Its weird, I know. I blame GitHub for how they created the numbering scheme.

**Comment by kbromund** [comment]
OK, but this version breaks something that was working before:
when I changed my code to:
    cdf_file_path = nemisis_data.save(output_path=hermes_nemisis._data_directory, overwrite=True)
it successfully created an nms CDF file in my data directory.
But now I get the error:
>           cdf_file_path = output_path / (self.meta["Logical_file_id"] + ".cdf")
E           TypeError: unsupported operand type(s) for /: 'str' and 'str'

/home/vscode/.local/lib/python3.10/site-packages/hermes_core/timedata.py:965: TypeError

**Comment by Alrobbertz** [comment]
Aah, yes. We updated the `save()` function to require a `Path` object instead of a str. You should update your code:
`cdf_file_path = nemisis_data.save(output_path=Path(hermes_nemisis._data_directory), overwrite=True)`

**Comment by kbromund** [comment]
but why is that necessary, when __init__.py already sets it to:
_data_directory = os.path.abspath(os.path.join(_package_directory, "data"))

**Comment by kbromund** [comment]
hmmm... so nothing I do with my "__init__.py" file has any effect?

**Comment by dbarrous** [comment]
#118 closing as merged and updated on hermes_core and have successfully testing parsing and generating file names with the new nemisis shortname. I'm going to close this issue and we can continue the conversation in the nemisis issue here: https://github.com/HERMES-SOC/hermes_nemisis/issues/24

@kbromund If you can take a look at the [PR](https://github.com/HERMES-SOC/hermes_nemisis/pull/25) Andrew linked above when you get a chance and review/approve that would be greatly appreciated since we need an approval from the instrument team.
