### ISSUE TITLE
Clean up documentation to remove mentions of SunPy

### ISSUE THREAD

**Issue by ehsteve** [HERMES-SOC/hermes_core#34]
Our docs are based on sunpy docs and still including many incorrect references to sunpy which is confusing.

**Comment by Alrobbertz** [comment]
@ehsteve I've started to take a look at this while I'm working in the user docs. There are several cases in the `util` modules that reference the `licenses/SUNPY.rst` license in the repo. (Ex. in [logger.py](https://github.com/HERMES-SOC/hermes_core/blob/558ee47f6f793155ddefecaa73c70c67c26916f2/hermes_core/util/logger.py#LL9C1-L10C1))

However, this license is not present in the [licenses](https://github.com/HERMES-SOC/hermes_core/tree/cdf_data/licenses) directory. Would you like me to remove these references or update them to point to the `LICENSE.md` file in the licenses directory?

**Comment by ehsteve** [comment]
Good catch. I'll fix it.

**Comment by Alrobbertz** [comment]
To be resolved in #54
