### ISSUE TITLE
Check if any required metadata attribute are None and provide understandable error if trying to save to a CDF

### ISSUE THREAD

**Issue by ehsteve** [HERMES-SOC/hermes_core#55]
If an attribute is None, you get a weird error from spacepy which is hard to interpret.
```
Failed: [undefined]IndexError: list assignment index out of range
```

**Comment by Alrobbertz** [comment]
@ehsteve Are you in favor of (1) catching and re-raising an Error, with a more meaningful message, or (2) catching an Error, writing a warning, and moving on with the conversion?

**Comment by ehsteve** [comment]
(3) raising our own error before spacepy raises one. 

Should we do a check of the type for each required attribute before trying to write the cdf? For example some attributes we expect to be datetime others should be strings. None should be None.

**Comment by Alrobbertz** [comment]
I updated to raise an error before spacepy. 

My gut feeling is not to check the data types of the attributes. This would be difficult to encode the expected data types for all of the attributes in the `schema.yaml` files and have them correspond to specific numpy/astropy/standard python types.
