### ISSUE TITLE
Provide an interface to the CDF Format Guide

### ISSUE THREAD

**Issue by Alrobbertz** [HERMES-SOC/hermes_core#62]
The HERMES yaml CDF Schema files closely encode the HERMES CDF Format Guide. By adding descriptions and possible examples to the schema yaml files we can provide better information when users are interested in learning more about the requirements and examples of specific attributes.

**Comment by ehsteve** [comment]
It would be good to also include in the docs. We could just include the yaml file but a more readable format would be better.

**Comment by ehsteve** [comment]
I don't think you need the gallery. You can, for example, render, csv files  as tables (see https://sublime-and-sphinx-guide.readthedocs.io/en/latest/tables.html). Not sure if there is something similar for yaml files. Should we consider converting our schema files from yaml to csv? It might makes things easier. Are we doing anything with the yaml files that we cannot easily replicate with csv?
