### ISSUE TITLE
Enable Multi-Dimensional Data within TimeData

### ISSUE THREAD

**Issue by Alrobbertz** [HERMES-SOC/hermes_core#66]
`astropy` and `spacepy` allow us to read and write multi-dimensional data to/from CDF files. However in our initial development we did not enable spectrogram plotting for multi-dimensional variables. To mitigate this we disallowed all multi-dimensional data in the `TimeData` container. 

This issue is to add spectrogram plotting to `TimeData` and re-enable the reading and writing of multi-dimensional time series data. 

requested by @joeymukherjee

**Comment by ehsteve** [comment]
@joeymukherjee could you expand on your use case? How many energy bands do you need per time bin?

**Comment by Alrobbertz** [comment]
Implemented in #93
