### ISSUE TITLE
The documentation cannot be built by readthedocs with spacepy as a dependency 

### ISSUE THREAD

**Issue by ehsteve** [HERMES-SOC/hermes_core#69]
Spacepy and pycdf require the CDF libraries which need to be installed in the container that readthedocs uses to build our documentation. Maybe we can have them use our container instead.

**Comment by ehsteve** [comment]
Looks like rtd does not support user provided containers see https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os

**Comment by Alrobbertz** [comment]
Is it possible to to install them on the fly with https://docs.readthedocs.io/en/stable/config-file/v2.html#build-commands ?

**Comment by ehsteve** [comment]
It may. The commands I think we need to run are from our own docker image build 
```
apt-get -y install make && \
    apt-get -y install curl && \
    apt-get -y install wget && \
    apt-get -y install gfortran && \
    wget https://spdf.gsfc.nasa.gov/pub/software/cdf/dist/cdf38_0/cdf38_0-dist-cdf.tar.gz && \
    tar zxvpf cdf38_0-dist-cdf.tar.gz && rm cdf38_0-dist-cdf.tar.gz && \
    apt-get -y install libncurses5-dev && \
    apt-get -y install gcc && \
    cd cdf38_0-dist && \
    make OS=linux ENV=gnu all && \
    make INSTALLDIR=/usr/local/cdf install && \
    cd ..
```

**Comment by ehsteve** [comment]
Based on this example wget is available and can grab stuff on the internet 

https://docs.readthedocs.io/en/stable/build-customization.html#support-git-lfs-large-file-storage
