### ISSUE TITLE
If units are not SI convertible then an error is thrown by TimeData

### ISSUE THREAD

**Issue by ehsteve** [HERMES-SOC/hermes_core#83]
For example, using the "counts" units leads to this error. We should support this unit as, at least one of our instruments (MERIT) will need it.

**Comment by Alrobbertz** [comment]
@ehsteve Do you want me to include this in #79 or would you like me to make a separate PR for this issue?

**Comment by ehsteve** [comment]
If it's easier you can just include it.

**Comment by Alrobbertz** [comment]
Fixed in #87
