### ISSUE TITLE
Add the ability to accept ndarrays or Quantity arrays for support data

### ISSUE THREAD

**Issue by ehsteve** [HERMES-SOC/hermes_core#92]
To make it easier for users when nothing more is really needed for input. Currently we only accept NDData objects which requires users to learn how to use them when it might not be necessary if the support data array is simple and doesn't need the functionality provided by that object.

**Comment by Alrobbertz** [comment]
I'm going to sue this an an opportunity to clean up they type hinting as well in `hermes_core`
